// <auto-generated />
using System;
using Hubtel.PosProxyData.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hubtel.PosProxyData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hubtel.PosProxyData.EntityModels.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<decimal>("AmountAfterCharges")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<string>("BranchId");

                    b.Property<string>("BranchName");

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<string>("ClientReference")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CustomerEmail");

                    b.Property<string>("CustomerName");

                    b.Property<bool>("CustomerPaysFee");

                    b.Property<string>("Description");

                    b.Property<string>("EmployeeEmail");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("EmployeePhone");

                    b.Property<string>("ExternalTransactionId");

                    b.Property<string>("MomoChannel");

                    b.Property<string>("MomoPhoneNumber");

                    b.Property<string>("MomoToken");

                    b.Property<string>("Note");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("PaymentType");

                    b.Property<string>("PosDevice");

                    b.Property<string>("SalesOrderId");

                    b.Property<string>("Status");

                    b.Property<string>("TransactionId");

                    b.Property<string>("TransactionSession");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ClientReference")
                        .IsUnique()
                        .HasFilter("[ClientReference] IS NOT NULL");

                    b.ToTable("PaymentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
