// <auto-generated />
using System;
using Hubtel.PaymentProxyData.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hubtel.PaymentProxyData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hubtel.PaymentProxyData.EntityModels.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId");

                    b.Property<decimal>("AmountAfterCharges")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<string>("BranchId");

                    b.Property<string>("BranchName");

                    b.Property<bool?>("ChargeCustomer");

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(20, 4)");

                    b.Property<string>("ClientReference")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CustomerMobileNumber");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Description");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("ExternalTransactionId");

                    b.Property<bool>("IsRefund");

                    b.Property<bool>("IsSuccessful");

                    b.Property<string>("MomoChannel");

                    b.Property<string>("MomoPhoneNumber");

                    b.Property<string>("MomoToken");

                    b.Property<string>("Note");

                    b.Property<string>("OfflineGuid")
                        .HasMaxLength(50);

                    b.Property<Guid?>("OrderId");

                    b.Property<DateTime?>("PaymentDate");

                    b.Property<string>("PaymentType");

                    b.Property<string>("PosDeviceId");

                    b.Property<string>("PosDeviceType");

                    b.Property<string>("ReceiptNumber");

                    b.Property<string>("Status");

                    b.Property<string>("TransactionId");

                    b.Property<string>("TransactionSession");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ClientReference")
                        .IsUnique()
                        .HasFilter("[ClientReference] IS NOT NULL");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("Hubtel.PaymentProxyData.EntityModels.SalesOrderZipFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId");

                    b.Property<string>("Bucketname");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Filename");

                    b.Property<string>("MimeType");

                    b.Property<bool>("Processed");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("SalesOrderZipFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
